backend:
  name: git-gateway
  branch: devel
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "assests"
    label: "Tiedot"
    folder: "src/assets"
    files:
      - label: "Toimijat"
        name: "toimijat"
        file: "src/assets/toimijat.json"
        fields:
          - label: "Hallitus"
            name: "hallitus"
            widget: "list"
            summary: '{{fields.who}} - {{fields.what}}'
            fields: 
              - {label: "Who", name: "who", widget: "string", default: "bob"}
              - {label: "What", name: "what", widget: "string", default: "janitor"}
          - label: "Tuottis"
            name: "tuottis"
            widget: "list"
            summary: '{{fields.who}} - {{fields.what}}'
            fields: 
              - {label: "Who", name: "who", widget: "string", default: "javk"}
              - {label: "What", name: "what", widget: "string", default: "pilot"}