backend:
  name: git-gateway
  branch: devel
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "assests"
    label: "Tiedot"
    files:
      - label: "Toimijat"
        name: "toimijat"
        file: "src/assets/toimijat.json"
        fields:
          - label: "Yhteystiedot"
            name: "yhteystiedot"
            widget: "list"
            summary: '{{fields.name}}'
            fields: 
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Value", name: "value", widget: "string"}
          - label: "Hallitus"
            name: "hallitus"
            widget: "list"
            summary: '{{fields.name}} - {{fields.title}}'
            fields: 
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
          - label: "Yhdenvertaisuus- ja hyvinvointivastaavat"
            name: "yhdenvertaiset"
            widget: "list"
            fields: 
              - {label: "Name", name: "name"}
              - {label: "Name2", name: "name2"}
              - {label: "Info", name: "info"}
          - label: "Toimihenkilöt"
            name: "toimihenkilot"
            widget: "list"
            summary: '{{fields.name}} - {{fields.title}}'
            fields: 
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
          - label: "Tuottantotiimi"
            name: "tuottis"
            widget: "list"
            summary: '{{fields.name}} - {{fields.title}}'
            fields: 
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}