backend:
  name: git-gateway
  branch: devel
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "org_data"
    label: "Tiedot"
    folder: "_assets/data"
    create: true
    fields:
      - {label: "Who", name: "who", widget: "string"}
      - {label: "What", name: "what", widget: "string"}
      - {label: "Group", name: "group", widget: "select", options: ["Hallitus", "Tuottis"]}
