backend:
  name: git-gateway
  branch: devel
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "org_data"
    label: "Toimijat"
    folder: "_assets/data"
    create: false
    fields:
      - label: "Hallitus"
        name: "hallitus"
        widget: "list"
        fields: 
          - {label: "Who", name: "who", widget: "string"}
          - {label: "What", name: "what", widget: "string"}
      - label: "Tuottis"
        name: "tuottis"
        widget: "list"
        fields: 
          - {label: "Who", name: "who", widget: "string"}
          - {label: "What", name: "what", widget: "string"}