backend:
  name: git-gateway
  branch: devel
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "assests"
    label: "Tiedot"
    files:
      - label: "Toimijat"
        name: "toimijat"
        file: "src/assets/toimijat.json"
        fields:
          - label: "Hallitus"
            name: "hallitus"
            widget: "list"
            summary: '{{fields.who}} - {{fields.what}}'
            fields: 
              - {label: "Kuka", name: "kuka", widget: "string", default: "bob"}
              - {label: "Pesti", name: "pesti", widget: "string"}
          - label: "Yhdenvertaisuus- ja hyvinvointivastaavat"
            name: "yhdenvertaiset"
            widget: "list"
            fields: 
              - {label: "Tyyppi", name: "tyyppi"}
              - {label: "Tyyppi2", name: "tyyppi2"}
              - {label: "Info", name: "info"}
          - label: "Toimihenkilöt"
            name: "toimihenkilot"
            widget: "list"
            summary: '{{fields.who}} - {{fields.what}}'
            fields: 
              - {label: "Kuka", name: "kuka", widget: "string", default: "bob"}
              - {label: "Pesti", name: "pesti", widget: "string"}
          - label: "Tuottantotiimi"
            name: "tuottis"
            widget: "list"
            summary: '{{fields.who}} - {{fields.what}}'
            fields: 
              - {label: "Who", name: "who", widget: "string", default: "javk"}
              - {label: "What", name: "what", widget: "string", default: "pilot"}